apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: channel-carrier
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: channel-carrier
  chart:
    git: ssh://git@github.com/ryans3a/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://10.0.1.6:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      CvQCChgKFggCGgYI9IaC+wUiCmFsbGNoYW5uZWwS1wIK1AIKCmFsbGNoYW5uZWwSRhI0CgtBcHBs
      aWNhdGlvbhIlEhMKD21hbnVmYWN0dXJlck1TUBIAEg4KCmNhcnJpZXJNU1ASABoOCgpDb25zb3J0
      aXVtEgAa/QES0QEKC0FwcGxpY2F0aW9uEsEBCAESDgoKY2Fycmllck1TUBIAEhMKD21hbnVmYWN0
      dXJlck1TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjFfMRIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxonCgpDb25z
      b3J0aXVtEhkSFwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVt