apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: instantiate-manufacturer-allchannel-supplychain1
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: instantiate-manufacturer-allchannel-supplychain1
  chart:
    git: ssh://git@github.com/ryans3a/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/instantiate_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://10.0.1.6:8200
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:1.4.4
      name: supplychain
      version: 1
      instantiationarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
